/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/fuOSwiWdpXi
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
'use client';
import React, { useState, useEffect, createContext   } from 'react';
import { Form} from "./components/form"
import { SidebarComponent} from "../../common/components/sidebar"
import {MenuResponsive} from "../../common/components/menuResponsive"
import {userContext, tableContext,handleClickContext,columnsContext} from "../../common/contexts/contexts"



export default function Crear() {
  const [showElements, setShowElements] = useState<boolean>(false); // Estado para controlar la visibilidad

  const handleClick = async () => {
    setShowElements(!showElements)
  };




  return (
    <div className="flex h-screen bg-gray-200 dark:bg-gray-900">
      <userContext.Provider value={showElements}>
        <handleClickContext.Provider value={handleClick}>
          <SidebarComponent />
        </handleClickContext.Provider>
      </userContext.Provider> 

      <Form> </Form>

      <MenuResponsive/>

      </div>
    );

}