/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/fuOSwiWdpXi
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
'use client';
import React, { useState, useEffect, createContext   } from 'react';
import { SidebarComponent} from "./components/sidebar"
import { Form} from "./components/form"

export const userContext = createContext({});
export const tableContext = createContext({});;
export const handleClickContext = createContext({});
export const columnsContext = createContext({});
export const personajeContext = createContext({});;


export default function consultar() {
  const [showElements, setShowElements] = useState<boolean>(true); // Estado para controlar la visibilidad

  const handleClick = async () => {
    setShowElements(!showElements)
  };




  return (
    <div className="flex h-screen bg-gray-200 dark:bg-gray-900">
      <userContext.Provider value={showElements}>
        <handleClickContext.Provider value={handleClick}>
          <SidebarComponent />
        </handleClickContext.Provider>
      </userContext.Provider> 

      <Form> </Form>
      </div>
    );

}