/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/fuOSwiWdpXi
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
'use client';
import React, { useState, useEffect, createContext   } from 'react';
import { SidebarComponent} from "./components/sidebar"
import { Form} from "./components/form"

import { useSearchParams } from 'next/navigation'


export const userContext = createContext({});
export const tableContext = createContext({});;
export const handleClickContext = createContext({});
export const columnsContext = createContext({});
export const personajeContext = createContext({});;


export default function listado() {
  const [showElements, setShowElements] = useState<boolean>(true); // Estado para controlar la visibilidad
  const [personaje, setPersonaje] = useState<any>({}); // Estado para controlar la visibilidad
  const [bool, setBool] = useState<any>(false); // Estado para controlar la visibilidad

  const handleClick = async () => {
    setShowElements(!showElements)
  };

  const searchParams = useSearchParams()

  useEffect(() => {
    const fetchCharacters = async () => {
      const id = searchParams.get('id');
      if(id){
        const personajes = JSON.parse(localStorage.getItem("characters"));
        const personajeNew = personajes.find(elemento => elemento.id == id);

        if(!personajeNew){
          alert('personaje no encontrado');
          return;
        }

        setPersonaje(personajeNew)
        setBool(true);
        //console.log(personajeNew)
      
      } 

      
    };
    if(!bool) fetchCharacters();

  }, []);

  return (
    <div className="flex h-screen bg-gray-200 dark:bg-gray-900">
      <userContext.Provider value={showElements}>
        <handleClickContext.Provider value={handleClick}>
          <SidebarComponent />
        </handleClickContext.Provider>
      </userContext.Provider> 

      {bool && <Form personaje={personaje}></Form>}

      
      <div className=" st-2 st-sticky-share-buttons st-left st-toggleable st-has-labels hidden ">
          <a className="st-btn st-first m-auto" data-network="whatsapp" href="#">
            <svg className="h-5 w-5 text-gray-500 dark:text-gray-400  m-auto " xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
            <div className="st-label">Charapters</div>
          </a>

          <a className="st-btn m-auto" data-network="whatsapp" href="#">
            <svg className="h-5 w-5 text-gray-500 dark:text-gray-400 m-auto" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M22 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
            <div className="st-label">Episodes</div>
          </a>
      </div>


      </div>
    );

}